### ISSUE TITLE
User Story 1: View a list of articles

### ISSUE THREAD

**Issue by reesegreen2014** [reesegreen2014/news-app#1]
### Acceptance Criteria:
- [x] The list should display the headline, image, description (if present), and date for each article.
- [x] Articles should be fetched from the News API.
- [x] Articles should be displayed in a responsive layout suitable for desktop, tablet, and mobile devices.
